"use strict";
exports.__esModule = true;
var web_1 = require("./web");
exports.Button = web_1.Button;
exports.Container = web_1.Container;
exports.Flex = web_1.Flex;
var globalStyle_1 = require("./utils/theme/globalStyle");
exports.GlobalStyles = globalStyle_1["default"];
var native_1 = require("./native");
exports.Grid = native_1["default"];
